name: Release validation CI
on:
  workflow_dispatch:
jobs:
  my_first_job:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Buildpack integration test
        uses: ./.github/actions/buildpack-integration-test